[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; === НАСТРОЙКИ ПАМЯТИ ДЛЯ ESP32-S3 N16R8 ===
; Явно указываем частоту и режим флеш-памяти
board_build.f_flash = 80000000L
board_build.flash_mode = dio
; Явно указываем размер флеш-памяти для загрузчика
board_upload.flash_size = 16MB
; ВАЖНО: Указываем таблицу разделов для 16 МБ, иначе компилятор будет думать, что у нас 8 МБ
board_build.partitions = default_16MB.csv
; Включаем PSRAM в режиме OPI
board_build.psram = opi
board_build.arduino.memory_type = qio_opi

; === СКОРОСТИ ===
upload_speed = 921600
monitor_speed = 115200

; === ОТКЛЮЧАЕМ USB CDC (чтобы Serial работал через UART) ===
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=0