[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.filesystem = littlefs
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

; === БИБЛИОТЕКИ ===
lib_deps = 
    me-no-dev/AsyncTCP @ ^1.1.1
    ESP Async WebServer
    bblanchon/ArduinoJson @ ^7.4.3
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    adafruit/Adafruit GFX Library @ ^1.11.11

; === ЗАПРЕЩАЕМ НЕПРАВИЛЬНУЮ БИБЛИОТЕКУ ===
lib_ignore = 
    AsyncTCP_RP2040W

lib_ldf_mode = deep+

; === НАСТРОЙКА USB ===
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1

upload_speed = 921600
monitor_speed = 115200

; === ДЛЯ РАЗНЫХ ПОРТОВ ===
upload_port = COM4       ; ← Для программирования (Windows)
monitor_port = COM4      ; ← Для отладки (Windows)
; monitor_port = COM6    ; ← Если хотите смотреть данные на Ubuntu